/// Plain-Dart events surfaced from a live model session, decoded from
/// whatever the SDK/session transport actually sends (see
/// `../data/gemini_live_repository.dart`, the only place that transport-level
/// type is touched). Nothing in this file imports `firebase_ai` — that is the
/// whole point of having this layer, per DESIGN.md §2.3.
sealed class LiveCallEvent {
  const LiveCallEvent();
}

/// A fragment of transcribed speech, either the user's own voice
/// (`fromUser: true`) or the model's spoken output. Fragments for the same
/// speaker are typically merged by the application layer (mirrors
/// `appendTranscript` in `useLiveSession.ts`).
final class LiveTranscriptFragment extends LiveCallEvent {
  const LiveTranscriptFragment({required this.text, required this.fromUser});

  final String text;
  final bool fromUser;
}

/// Raw PCM16 audio bytes generated by the model (24kHz mono), ready to hand
/// to the playback pipeline.
final class LiveAudioChunk extends LiveCallEvent {
  const LiveAudioChunk(this.pcm16);

  final List<int> pcm16;
}

/// The server's own barge-in signal: its VAD detected the user speaking while
/// it was still generating/streaming audio. This is the *authoritative*
/// barge-in trigger — see DESIGN.md §3.5.
final class LiveInterrupted extends LiveCallEvent {
  const LiveInterrupted();
}

/// The model finished its turn and is waiting for the next user input.
final class LiveTurnComplete extends LiveCallEvent {
  const LiveTurnComplete();
}

/// The model invoked a tool (only `flagRelapseRisk` exists today — see
/// `RelapseStage`). The application layer is responsible for calling back
/// into the repository with a tool response.
final class LiveToolCallRequested extends LiveCallEvent {
  const LiveToolCallRequested({
    required this.callId,
    required this.name,
    required this.args,
  });

  /// Correlates a response back to this specific call, when the SDK provides
  /// one. May be null.
  final String? callId;
  final String name;
  final Map<String, Object?> args;
}

/// The session closed, whether cleanly or due to an error. `error` is a
/// plain-language, UI-safe message (mirrors `AppException`'s contract) or
/// null for a clean close.
final class LiveSessionClosed extends LiveCallEvent {
  const LiveSessionClosed({this.error});

  final String? error;
}
